CREATE TABLE result (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id  UUID         NOT NULL UNIQUE,
    user_id     BIGINT       NOT NULL,
    action      VARCHAR(255) NOT NULL,
    result      BOOLEAN      NOT NULL,
    created_at  TIMESTAMP    NOT NULL
);